### ISSUE TITLE
'Unknown word' error with myfonts counter import

### ISSUE THREAD

**Issue by PhilRedm** [unlight/postcss-import-url#1]
I get the following error:

`Error: postcss-import-url: <css input>:1:1: Unknown word`

when this import is in my source:

`@import url("//hello.myfonts.net/count/3022f1");`

Any advice on getting around this issue?

**Comment by unlight** [comment]
I think you must explicitly provide protocol of url (http or https).

**Comment by PhilRedm** [comment]
Adding the protocol does prevent the error but in that case the @import is not processed, but is passed through to the output.

**Comment by unlight** [comment]
Please, provide more info (what version of post-css, node, platform, etc.) 
I'll take a look at it tomorrow.

Also, `http://hello.myfonts.net/count/3022f1` is it example or real path?

**Comment by PhilRedm** [comment]
MacOS 10.10.5 (14F1605)
NPM 3.3.9

```
"cssnano": "^3.5.2",
"gulp": "^3.9.0",
"gulp-postcss": "^6.0.1",
"postcss": "^5.0.14",
"postcss-cssnext": "^2.4.0",
"postcss-import": "^8.0.2",
"postcss-import-url": "^1.0.0"
```

The include as provided by MyFonts is:

`@import url("//hello.myfonts.net/count/3022f1")`

Thanks for your help.

**Comment by unlight** [comment]
What content are you expect?
`http://hello.myfonts.net/count/3022f1` gives me empty document.
I have checked for error `unknown word`, and it come from `postcss\lib\parser.js`
Which reference to wrong css syntax.
Can you provide entire css file?

**Comment by PhilRedm** [comment]
I found an explanation here:
http://stackoverflow.com/questions/23045705/how-the-licensed-web-font-is-getting-rendered

Apparently this import is not mandatory so I've removed it with no ill-effect. Sorry to waste your time on this.
