### ISSUE TITLE
Upgrade postcss dependency to ^6.0.0

### ISSUE THREAD

**Issue by GreenGremlin** [unlight/postcss-import-url#11]
Opening this issue to discuss adding support for postcss@6.

### Breaking changes

1. The behavior of `Node#append` has changed, but only when passing a node that already has a parent.

    _This package [uses append](https://github.com/unlight/postcss-import-url/blob/master/index.js#L34) but it only appends new nodes, so this should not be a concern_

2. The `move`, `moveAfter` & `moveBefore` functions are deprecated.

    _Not used by this package._

3. The `clone` function has changed.

     _Not used by this package._

4. Support for Node 0.12 was dropped.

    _Should this package support postcss@5 and postcss@6?_

Release notes for postcss: https://github.com/postcss/postcss/releases/tag/6.0.0

**Comment by GreenGremlin** [comment]
I upgraded to `postcss@6.0.13` and, after [addressing some indentation conflicts](https://github.com/unlight/postcss-import-url/pull/12/commits/5e48453c7043093760399968d960cc07a46bbac4), all tests passed.

**Comment by unlight** [comment]
[Published v3.0.1](https://github.com/unlight/postcss-import-url/releases)
