### ISSUE TITLE
Setting element's `source` property

### ISSUE THREAD

**Issue by AaronJan** [unlight/postcss-import-url#27]
Hi, handy plugin, love this. 😄 

I created a postcss plugin: [`postcss-font-grabber`](https://github.com/AaronJan/postcss-font-grabber). [@FTWinston](https://github.com/FTWinston) use it with `postcss-import-url`, found an issue: https://github.com/AaronJan/postcss-font-grabber/issues/20.

According to [the postcss docs](https://postcss.org/api/#atrule):

> If you create a node manually (e.g., with postcss.decl()), that node will not have a source property and will be absent from the source map. For this reason, the plugin developer should consider cloning nodes to create new ones (in which case the new node’s source will reference the original, cloned node) or setting the source property manually.

I think we could set the `source` property for imported elements (as the same as the `@import` statement is in), to improve the compatibility, so `postcss-import-url` can works with some other plugins.

What do you think? Thanks! 🤝

**Comment by unlight** [comment]
Hi. I think if this recommendation or best practice of PostCSS we should follow it.

I'll try to fix it, but I do not know when.

Feel free to send PR if it's urgent.

**Comment by AaronJan** [comment]
> Hi. I think if this recommendation or best practice of PostCSS we should follow it.
> 
> I'll try to fix it, but I do not know when.
> 
> Feel free to send PR if it's urgent.

I'll see what I can do tomorrow, cheers. 😄
