### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by MatthewVance** [unlight/postcss-import-url#6]
Great plugin. One thing I noticed while testing is Google fonts returns different file types per the user agent. Because this tool runs in a shell, Google returns truetype fonts rather than the better woff2 format. I'm not sure this can be easily resolved by the tool since Google attempts to return the best font file type based on user agent. However, it might be worth posting a warning in the [README.md](https://github.com/unlight/postcss-import-url/blob/master/README.md).

For example, I have a file which has:
`@import url("https://fonts.googleapis.com/css?family=Roboto:300,400,500,700");/*!`

The output includes:

```
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light'), local('Roboto-Light'), url(https://fonts.gstatic.com/s/roboto/v15/Hgo13k-tfSpn0qi1SFdUfaCWcynf_cDxXwCLxiixG1c.ttf) format('truetype');
}
...
```

If you go to https://fonts.googleapis.com/css?family=Roboto:300,400,500,700 in Chrome, you should see output that includes:

```
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light'), local('Roboto-Light'), url(https://fonts.gstatic.com/s/roboto/v15/Hgo13k-tfSpn0qi1SFdUfZBw1xU1rKptJj_0jans920.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
...
```

**Comment by unlight** [comment]
Thanks. Added notice to [README](https://github.com/unlight/postcss-import-url#known-issues).
I think issue can be fixed by adding User-Agent http header.
I'll keep this issue open.

**Comment by MatthewVance** [comment]
Thanks. My concern is the static nature of this. Newer font formats aren't supported by all browsers so I'm worried forcing the best format might break compatibility in some cases. I may be wrong so it'd be great if you can get this to work.

**Comment by outdooricon** [comment]
This plugin is exactly what I'm looking for, but I need woff/woff2 and can't use it until this is solved. You could allow for a config option specifying what level of compatibility is needed for the User-Agent
